config/routes.rb
Rails.application.routes.draw do
  root 'pages#dashboard'

  get '/index', to: 'pages#index', as: 'index'
  get '/dashboard', to: 'pages#dashboard', as: 'dashboard'
  get '/followers', to: 'pages#followers', as: 'followers'

  get '/auth/github/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :uid, presence: true, uniqueness: true
  validates :username, presence: true, uniqueness: true
  validates :name, presence: true
  validates :image_path, presence: true
  

  def self.sign_in_from_omniauth(auth)
    find_by(uid: auth['uid']) || create_user_from_omniauth(auth)
  end

  def self.create_user_from_omniauth(auth)
    create!(
      uid: auth['uid'],
      name: auth['info'].name,
      username: auth['info']['nickname'],
      image_path: auth['info']['image'],
      token: auth['credentials']['token'],
      repo_count: auth['extra']['raw_info']['public_repos'],
      follower_count: auth['extra']['raw_info']['followers'],
      following_count: auth['extra']['raw_info']['following']
      )
  end

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_auth
  def index
    redirect to dashboard_path if current_user
  end

  def dashboard
    redirect_to index_path if !current_user
    if current_user
      gs = GithubService.new(current_user.username, current_user.token)
      @repos = gs.get_repo_data
      @rate_limit = gs.rate_limit
      @search_limit = gs.search_limit
      @followers = gs.get_followers_data
      @pulls = gs.get_pull_data
      @starred = gs.starred_repos.count
      @orgs = gs.organizations.count
      @commits = gs.get_commit_data
    end

    def followers
      gs = GithubService.new(current_user.username, current_user.token)
      @events = gs.get_followers_activity.flatten
    end

  end

private

  def set_auth
    @auth = session[:omniauth] if session[:omniauth]
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

def create
  auth = request.env["omniauth.auth"]
  session[:omniauth] = auth.except('extra')
  user = User.sign_in_from_omniauth(auth)
  session[:user_id] = user.id
  redirect_to dashboard_path if current_user
  redirect_to index_path if !current_user
end

def destroy
  session[:user_id] = nil
  session[:omniauth] = nil
  redirect_to root_url, notice: "Signed Out"
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Ihub</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
	<link rel="stylesheet" href="app/assets/stylesheets/custom.css">
	<link rel="stylesheet" href="app/assets/stylesheets/animate.css">

</head>
<body>

	<%= render partial: "partials/navbar" %> 
	<%= render partial: "partials/flashes" %>


	<div class="col-md-9">
		<%= yield %>
	</div>

	<div class="container-fluid col-md-3 sidebar">	
	<%= render partial: "partials/sidebar" %>
	</div>

</body>
</html>

app/views/pages/dashboard.html.erb
<div class="col-md-4 list-group">
<a href="#" class="list-group-item active"><h2>Repositories:</h2></a>
<div class="repo-list">
	<% @repos.each do |repo| %>
	<a href="<%= repo.html_url %>" class="list-group-item"><h3><%= repo.name %></h3>
		updated <%= time_ago_in_words(repo.updated_at) %> ago</a>
<% end %>
</div>
</div>

<div class="col-md-4 list-group">
<a href="#" class="list-group-item active"><h2>Pull Requests:</h2></a>
<div class="repo-list">
	<% @pulls.each do |pull| %>
	<a href="<%= pull[:html_url] %>" class="list-group-item"><b><%= pull[:title] %></b>
		<%= pull[:state] %><br>
		updated <%= time_ago_in_words(pull[:updated_at]) %> ago</a>
<% end %>
</div>
</div>

<div class="col-md-4 list-group">
<a href="#" class="list-group-item active"><h2>Commits:</h2></a>
<div class="repo-list">
	<% @commits.each do |commit| %>
	<a href="<%= commit[:commit][:html_url] %>" class="list-group-item"><b><%= commit[:commit][:message] %></b>
		updated <%= time_ago_in_words(commit[:commit][:author][:date]) %> ago</a>
<% end %>
</div>
</div>

app/views/pages/followers.html.erb
<div class="col-md-8 list-group">
<a href="#" class="list-group-item active"><h2>Follower Events:</h2></a>
<div class="repo-list">
	<% @events.each do |event| %>
	<a href="<%= event.html_url %>" class="list-group-item"><h3><%= event.name %></h3>
		updated <%= time_ago_in_words(event.updated_at) %> ago</a>
<% end %>
</div>
</div>

app/views/pages/index.html.erb
<p align="center">
<h1>Welcome to Imithub</h1>
Please log in with Github to continue.</p>

app/views/partials/_flashes.html.erb
<% flash.each do |key, value| %>
 <div class="alert alert-info trans" id="flash"><%= value %></div>
<% end %>

	<% if current_user %>
	<div class="text-center login-float" id="flash2">
		<h1>Welcome, <%= current_user.name %></h1>
		<h4>Logged in with <strong><em> Github </em></strong></h4>
		<%= image_tag('bestopus.png', width: '200') %>
	</div>
	<% end %>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-inverse">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
				</button>
				<div class="navbar-brand imithub"><%= link_to root_path do %><%= image_tag('bestopus.png', width: '40', class: "navbar-img") %>ImitHub<% end %></div>
			</div>

			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav navbar-right">
					<% if current_user %>
					<li>Signed in as <%= current_user.username %>
						<div class="circle-avatar" style="background-image:url(<%= current_user.image_path %>)"></div><br>
					<li><%= button_to "Sign Out", 'logout', method: :delete, class: "btn btn-info log-out btn-xs" %></li>
					<% else %>
					<li><%= button_to 'auth/github',  class: "btn btn-info log-in" do %>Sign in with <%= image_tag('octocat.png', width: '45', height: '40') %><% end %></li>
					<% end %>
				</ul>
			</div>
		</div>
	</nav>

app/views/partials/_search.html.erb
<form class="form-group form-inline float-right" role="search">
	<div class="form-group">
		<input type="text" class="form-control search-bar" placeholder="Search">
	</div>
	<%= button_to "Submit", class: "btn btn-info btn-sm search-butt", method: "GET" %>
</form>

app/views/partials/_sidebar.html.erb
<%= render partial: "partials/search" %>
<div class="bar-list well">
	<% if current_user %>
	<h3>Stats:</h3>
<%= link_to "#{current_user.follower_count} Followers", followers_path %> <br>
Following <%= current_user.following_count %><br>
<%= current_user.repo_count %> Repos<br>
Starred Repos: <%= @starred %><br>
Organizations: <%= @orgs %><br>
<br>
Rate Limit: <%= @rate_limit %><br>
Search Limit: <%= @search_limit %>
</div>
<% end %>